<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Ajaxcatalog
 * @version    1.0.5
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/**
 * @see AW_Ajaxcatalog_Block_Catalog_Product_List
 */
?>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>    
</div>
<div class="awac-catalog-container" id="awac_catalog_container">   
    <?php echo $this->getNativeListHtml(); ?>    
</div>

<?php if ($this->needAjaxLoad()): ?>
    <?php if ($this->getActionType() == AW_Ajaxcatalog_Model_System_Config_Source_Actiontype::TYPE_BUTTON): ?>
        <div class="awac-button" id="awac_button">
            <?php echo $this->getButtonHtml(); ?>
        </div>    
    <?php else: ?>
        <div class="awac-loader" id="awac_loader">
            <?php echo $this->getLoaderHtml(); ?>
        </div>    
    <?php endif; ?>
    <?php if ($url = $this->getNextJumpUrl()): ?>
        <div class="robot-link">
            <a href="<?php echo $url; ?>" title="<?php echo $this->__('More products'); ?>"><?php echo $this->__('More products'); ?></a>
        </div>
    <?php endif; ?>

    <script type="text/javascript">
        var _ajaxCatalog = new AWAjaxCatalog({
            'page_count': <?php echo $this->getPageCount() ? $this->getPageCount() : 0; ?>,
            'current_page': <?php echo $this->getCurrentPage() ? $this->getCurrentPage() : 1; ?>,
            'container_id': 'awac_catalog_container',
            'button_id': 'button_label',
            'button_container_id': 'awac_button',
            'loader_id': 'loader_label',
            'next_page': <?php echo $this->getNextPageNum() ?>,        
            'next_url': '<?php echo $this->getUrl('awajaxcatalog/load/next', array('pa' => '{{page}}')) ?>',
            'params': <?php echo $this->getFilterParams(); ?>,
            'route': '<?php echo $this->getRoute(); ?>',
            'action_type': '<?php echo $this->getActionType(); ?>',
            'decorate_clean': 'div.awac-catalog-container ul.products-grid, div.awac-catalog-container ol.grid-row, div.awac-catalog-container .products-list li.item',
            'decorate_decorate': ['div.awac-catalog-container ul.products-grid', 'div.awac-catalog-container ol.grid-row', 'div.awac-catalog-container .products-list li.item']            
        });
    </script>

<?php endif; ?>

<div class="category-products">
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>    
</div>


<?php /*  Back To Top  link */ ?>
<?php if (Mage::getStoreConfig('awajaxcatalog/general/backtotop_enabled')): ?>
    <?php
    $str = (strlen(Mage::getStoreConfig('awajaxcatalog/general/backtotop_label'))) ? addslashes(htmlspecialchars(Mage::getStoreConfig('awajaxcatalog/general/backtotop_label'))) : "Back to Top";
    ?>
    <script type="text/javascript">
                                
        var awac_backtotop_selector='div.main';
        var awan_backtotop_main=$$(awac_backtotop_selector).first();
        if(awan_backtotop_main){
            awacBackToTop = {
                initialize: function() {
                    awan_backtotop_main.appendChild(
                    awacBackToTop.link = new Element('div', {id: 'awac-back-to-top'})
                    .update("<?php echo $str; ?>")
                    .setOpacity(0.6)
                );
                    awacBackToTop.link.observe("click", awacBackToTop.onLinkClick);
                    Event.observe(window, "scroll", awacBackToTop.onWindowScroll);
                },
                onLinkClick: function() {
                    if (window.location.hash) {
                        window.location.hash = "page";
                    } else {
                        window.scrollTo(0, 0);
                    }
                },
                onWindowScroll: function() {
                    var main_width=awan_backtotop_main.getDimensions().width;
                    var window_width=document.viewport.getWidth();
                    var hrpos=((window_width-main_width)/2+75).round();
                    awacBackToTop.link.setStyle({'right' : hrpos + 'px' });
                                                            
                    var pos_xy=document.viewport.getScrollOffsets();
                    if (pos_xy[1] > (document.viewport.getHeight() * 0.8)) {
                        awacBackToTop.link.addClassName('visible');
                    } else {
                        awacBackToTop.link.removeClassName('visible');
                    }
                }
            };
            Event.observe(window, 'load', awacBackToTop.initialize);
        }
    </script>
<?php endif; ?>    
