<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.6.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$rule = Mage::registry('points_rule_data');
?>
<script type="text/javascript">

    function saveAs(){
        value = prompt('<?php echo Mage::helper('points')->__('Please enter new rule name') ?>', '<?php echo Mage::helper('points')->__('Copy ') . $rule->getName() ?>');
        if(!value) {
            return false;
        } else {
            $('rule_name').value = value;
        }

        $('rule_save_as_flag').value = '1';

        editForm.submit();
        return false;
    }

</script>