<?php 
$inviter = $this->getInviter();
$contacts = $inviter->getMyContacts();
?>
<?php if ($inviter->showContacts()){ 
if (count($contacts)==0) echo $this->__('You do not have any contacts in your address book.');
else{
?>
<form action="<?php echo $this->getUrl('rewardpoints/invitation/submitmail');?>" name="form_submit_new" id="form_submit_new" method="post">
<div style="height: 380px; width: 450px; overflow-y: auto;">
	<table class="data-table">
	    <thead>
	        <tr>
				<th style="text-align: center;"><input type='checkbox' onChange='toggleAll(this)' name='toggle_all' title='Select/Deselect all'><?php //echo $this->__(' check') ?></th>
				<th style="text-align: center;"><?php echo $this->__('Name') ?></th>
				<th style="text-align: center;"><?php echo $this->__('Email') ?></th>
	        </tr>
	    </thead>
	    <tbody>
	        <?php foreach($contacts as $email=>$name){ ?>
	            <tr style="text-align:left">
	                <td><input type="checkbox" name="mw_contact_mail[]" value="<?php echo $email?>" /></td>
					<td><?php echo $name;?></td>
					<td><?php echo $email;?></td>
	            </tr>
	        <?php }?>
	    </tbody>
	</table>

</div>
<div style="clear: both;padding: 8px 0 0; text-align: right; width: 450px;">  
	  <p class="back-link" style="text-align: left;"><a href="<?php echo $this->getUrl('rewardpoints/invitation/loginmail') ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p> 	
      <button type="submit" title="<?php echo $this->__('Add Contact') ?>" id="mw_submit" class="button"><span><span><?php echo $this->__('Add Contact') ?></span></span></button>
</div>
</form>
<script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form_submit_new', true);
        function toggleAll(element) 
    	{
    	var form = document.forms.form_submit_new, z = 0;
    	for(z=0; z<form.length;z++)
    		{
    		if(form[z].type == 'checkbox')
    			form[z].checked = element.checked;
    	   	}
    	}
    //]]>
    </script>
<?php  }
}
?>