<?php 
 $_source  = $this->getSource();
 $_order = $this->getOrder();

 $this->setPriceDataObject($_source); 
 
 $baseCurrencyCode = Mage::getModel('sales/order')->load($_order->getId())->getData('base_currency_code');
 $currentCurrencyCode = Mage::getModel('sales/order')->load($_order->getId())->getData('order_currency_code');
 
 $rewardOrder = Mage::getModel('rewardpoints/rewardpointsorder')->load($_order->getId());
 $store_id = Mage::getModel('sales/order')->load($_order->getId())->getStoreId();
 $reward_point_discount = $_order->getMwRewardpointDiscount();
 $reward_point_discount_show = $_order->getMwRewardpointDiscountShow();
 if($reward_point_discount == 0) $reward_point_discount = $rewardOrder->getMoney();
 if($reward_point_discount_show == 0) $reward_point_discount_show = Mage::helper('directory')-> currencyConvert($rewardOrder->getMoney(),$baseCurrencyCode, $currentCurrencyCode);
 

 $rewardpoints = (int)$this->getOrder()->getMwRewardpoint();
 if($rewardpoints == 0) $rewardpoints = $rewardOrder->getRewardPoint();



if ($reward_point_discount > 0){ 
$value  = - $reward_point_discount;
$value_show = - $reward_point_discount_show;
if($_source instanceof Mage_Sales_Model_Order_Creditmemo) $value =  - $value;?>
    <tr>
        <td class="label"><?php echo Mage::helper('rewardpoints')->__('You Redeemed(%s)',trim(Mage::helper('rewardpoints')->formatPoints($rewardpoints,$store_id))); ?></td>
        <td>
            <?php echo $this->displayPrices($value, $value_show); ?>
        </td>
    </tr>
<?php }; ?>
