<?php
/**
 * i95Dev.com
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://store.i95dev.com/LICENSE-M1.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@i95dev.com so we can send you a copy immediately.
 *
 * @category
 * @package        I95Dev_I95DevConnect
 * @Description    To View the order id for ofline order
 * @author         I95Dev
 * @copyright      Copyright (c) 2013 i95Dev
 * @license        http://store.i95dev.com/LICENSE-M1.txt
 */
?>
<?php
$targetOrderId = $this->getTargetOrderId();
?>


<table cellspacing="0" class="form-list">
    <tr>
        <td class="label"><label><?php echo "GP Order ID"; ?>
            </label></td>
        <td style="font-weight: bold;"><?php echo strtoupper($targetOrderId); ?>
        </td>
    </tr>
    <tr>
        <td class="label"><label><?php echo 'GP Order Status'; ?>
            </label></td>
        <td style="font-weight: bold;">New</td>
    </tr>
</table>
