<form id="form-validate" method="post" action="<?php echo $this->getUrl('rewardpoints/rewardpoints/send')?>">
    <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <h2 class="legend"><?php echo $this->__("Send Reward Points To Friend")?></h2>
        <ul class="form-list">
            <li class="fields">
			    <div class="field">
			        <label class="required" style="color:#666666" for="email"><?php echo Mage::helper('rewardpoints')->__('Email of your friend');?><em style="color:#EB340A">*</em></label>
			        <div class="input-box">
			            <input type="text" class="input-text required-entry validate-email" title="Email" name="email" id="email" gtbfieldid="135">
			        </div>
			    </div>
			    <div class="field">
			        <label class="required" style="color:#666666" for="name"><?php echo Mage::helper('rewardpoints')->__('Friend name');?><em style="color:#EB340A">*</em></label>
			        <div class="input-box">
			            <input type="text" class="input-text required-entry" title="Name" name="name" id="name" gtbfieldid="135">
			        </div>
			    </div>
            </li>
           
            <li class="fields">
		        <div class="field">
		        	<label class="required" style="color:#666666" for="amount"><?php echo Mage::helper('rewardpoints')->__('Points to send');?><em style="color:#EB340A">*</em></label>
		        	<div class="input-box"><input type="text" class="input-text required-entry validate-digits" title="Amount" name="amount" id="amount" gtbfieldid="136"></div>
		        </div>
		        <div class="field">
					<label for="message"><?php echo $this->__('Message') ?></label>
                    <div class="input-box">
                    	<textarea class="input-text" title="<?php echo $this->__('Message') ?>" name="message" id="message" ></textarea>
                    </div>
			    </div>
            </li>
            <li>
                <div class="buttons-set">
                	<p class="required"><?php echo Mage::helper('rewardpoints')->__("* Required Fields");?></p>
			        <button class="button" title="<?php echo Mage::helper('rewardpoints')->__("Send");?>" type="submit"><span><span>  <?php echo Mage::helper('rewardpoints')->__("Send");?>  </span></span></button>
			    </div>
            </li>
        </ul>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    //]]>
</script>