<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento community edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento community edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Affiliate
 * @version    1.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
if ($this->getRequest()->getParam(AW_Affiliate_Helper_Data::USE_AW_BACKURL_FLAG)
    && ($backUrl = Mage::helper('awaffiliate')->getBackUrl())
) : ?>
<script type="text/javascript">
    $$('button.back').each(function (el) {
        if ((typeof el == 'object') && el.hasAttribute('onclick')) {
            el.setAttribute('onclick', "setLocation('<?php echo $backUrl ?>')")
        }
    });
</script>
<?php endif;
